version: "0.0"

services:
  uhppoted-simulator:
    container_name: uhppoted-simulator
    restart: unless-stopped
    image: ghcr.io/uhppoted/simulator:latest
    volumes:
      - uhppoted:/usr/local/etc/uhppoted
    ports:
      - "60000:60000/udp"
      - "60000:60000"
      - "8000:8000"

volumes:
  uhppoted:
